spring:
  datasource:
#    url: jdbc:mysql://10.172.216.113/db_mall
#    username: mall
#    password: cm1ZwY0MrMZSoUvcowr5
    url: jdbc:mysql://localhost/db_scheduler?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

scheduler:
  core:
    component:
      init:
        init-scheduler:
          cron-key: cron-key
      daemon:
        job-scan:
          cron: "* * * * * ?"

  job:
    task:
      report-job:
        path: "/Users/docryze/temp/"